NDefines.NGame.MAP_SCALE_PIXEL_TO_KM = 0.5
NDefines.NBuildings.AIRBASE_CAPACITY_MULT = 50
NDefines.NMilitary.LAND_SPEED_MODIFIER = 0.75
NDefines.NAir.AIR_WING_FLIGHT_SPEED_MULT = 0.3
NDefines.NNavy.NAVAL_SPEED_MODIFIER = 1.5
NDefines.NNavy.NAVAL_RANGE_TO_INGAME_DISTANCE = 1.8